### ISSUE TITLE
feature: Add support for Guids

### ISSUE THREAD

**Issue by molostovvs** [ydb-platform/ydb-dotnet-sdk#187]
# Feature Request

**Describe the Feature Request**

Add support for `Guid`.

**Describe Preferred Solution**

**Describe Alternatives**

Now guid can be stored in a column of type string.

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
`Yes` / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by KirillKurdyukov** [comment]
This option looks attractive. But the problem is that the UUID can become a tabular type. Then you can't do without breaking backward compatibility. And this will mean changing the column types.
