### ISSUE TITLE
Error ClientTransportTimeout

### ISSUE THREAD

**Issue by ClaymorePlay** [ydb-platform/ydb-dotnet-sdk#38]
When creating a session through Createsession, I get a ClientTransportTimeout error, regardless of the set timeout (was 20 minutes), there is no response from the server.

Through ydb cli, requests are executed successfully, the server responds. Initialize driver method works.
Version is Ydb.Sdk 0.1.0

```
var poolConfig = new SessionPoolConfig();
var fieldInfo = typeof(SessionPoolConfig).GetField("<CreateSessionTimeout>k__BackingField", BindingFlags.Instance | BindingFlags.NonPublic);
fieldInfo?.SetValue(poolConfig, TimeSpan.FromMinutes(20));

var tableClient = new TableClient(driver, new TableClientConfig(poolConfig));

var session = await tableClient.CreateSession(new CreateSessionSettings
{
    OperationTimeout = TimeSpan.FromMinutes(20),
    TransportTimeout = TimeSpan.FromMinutes(20),
});
```

**Comment by ClaymorePlay** [comment]
Problem solved by enabling VPN

**Comment by rekby** [comment]
@ClaymorePlay 
Thanks for the issue and notice about problem solved
