### ISSUE TITLE
feat: implement query service

### ISSUE THREAD

**Issue by rekby** [ydb-platform/ydb-dotnet-sdk#53]
With two methods:
1. Query("query text", query_params, optional transaction mode, lambda (result stream))
2. QueryTx(optional transaction mode, lambda(tx))

lambda is retriable user callback. When use queryTx - transaction will commit by default and has way for rollback (exception + tx.Rollback()).

And see to spanner.

Roadmap:

- [ ] Implement .Query() - method for single SQL execution without transaction creation
- [ ] Implement .QueryTx() method for multiple SQL executions on same transaction
    _waiting for Begin/Commit/Rollback transaction methods will be realized on server_ (at the moment transactions works using TableService methods)
- [ ] Session attach/detach
- [ ] Merge implementation of SessionPools from Query and Table services
  - [ ] Attach 
  - [ ] Detach
- [ ] Retryer
- [ ] Examples
- [ ] helper methods such as Select, SelectFirstOrDefault, NonQuery etc.

**Comment by KirillKurdyukov** [comment]
The first implementation was extremely unsuccessful.
