### ISSUE TITLE
bug: Test of recreate session

### ISSUE THREAD

**Issue by rekby** [ydb-platform/ydb-dotnet-sdk#68]
https://github.com/ydb-platform/ydb-dotnet-sdk/blob/512230633e729a818e4cc421dfe927cf303bfb61/src/Ydb.Sdk/tests/Table/TestGracefulShutdown.cs#L26

**Comment by KirillKurdyukov** [comment]
Server block - https://github.com/ydb-platform/ydb/issues/4507
