### ISSUE TITLE
ClientTransferTimeoutException without additional information

### ISSUE THREAD

**Issue by Artikud** [ydb-platform/ydb-dotnet-sdk#7]
`
var credentials = new ServiceAccountProvider(saFilePath: "Keys/key.json");

            await credentials.Initialize();
            var driver = new Driver(
                new DriverConfig(
                    "endpoint",
                    "database",
                    credentials));
            await driver.Initialize();
            var tableClient = new TableClient(driver);
            var response = await tableClient.SessionExec(async session =>
            {
                var query = $@"
                            DECLARE $id AS String;
                            SELECT *
                            FROM <table>
                            WHERE id = $id;";

                return await session.ExecuteDataQuery(
                    query: query,
                    txControl: TxControl.BeginSerializableRW().Commit(),
                    parameters: new Dictionary<string, YdbValue> { { "$id", YdbValue.MakeUtf8("id") } });
            });

            response.Status.EnsureSuccess();`
            
            
            

Throw exception 
![image](https://user-images.githubusercontent.com/6334430/228951019-c7200689-ddae-45c5-b196-44ed7d1ed1b2.png)

**Comment by Dorialean** [comment]
Same problem.

**Comment by Caraul** [comment]
`DriverConfig` contains `DefaultTransportTimeout` which by default is `TimeSpan.FromMinutes(1)` and big enough to handle all transport actions done through Driver. `CreateSession()` from `TableClient` may override `TransportTimeout` but may not - in that case transport timeout is delegated to one from `Driver`.
On the other side `SessionExec()` uses session pool which is configured by `SessionPoolConfig`. `GetSession()` from pool internally calls `CreateSession()` but always override transport timeout with `CreateSessionTimeout` from `SessionPoolConfig` - and that `CreateSessionTimeout` is by default just `TimeSpan.FromSeconds(1)` and obviously too small. Moreover `CreateSessionTimeout` is internal and not settable - double strike. Sessions from pool appears non-usable except transport is very fast.
Until changes in SDK I see only two workarounds - either always use `CreateSession()` or fix `SessionPoolConfig` through reflection:

```
var sessionPoolConfig = new SessionPoolConfig();
var fieldInfo = typeof(SessionPoolConfig).GetField("<CreateSessionTimeout>k__BackingField", BindingFlags.Instance | BindingFlags.NonPublic);
fieldInfo!.SetValue(sessionPoolConfig, TimeSpan.FromSeconds(3));
using var tableClient = new TableClient(driver, new TableClientConfig(sessionPoolConfig));

```
